### ISSUE TITLE
Issues with fine-tuning GPT2

### ISSUE THREAD

**Issue by LLLLLearn** [iwangjian/TRIP#3]
Hello author, In the process of fine-tuning GPT2 --use_control this parameter is set to true?

**Comment by iwangjian** [comment]
Hi, we proposed two variants to fine-tune GPT-2 for dialogue generation. Please set `--use_control false` for prompt-based generation while setting `--use_control true` for plan-controlled generation.

**Comment by LLLLLearn** [comment]
Thank you for your reply.
