### ISSUE TITLE
Asks about parameter Settings when running the evaluation function

### ISSUE THREAD

**Issue by LLLLLearn** [iwangjian/TRIP#4]
Hello author, when I run the code of the evaluation function, the path setting of the parameters is not particularly clear, such as <path_to_gold_data> this parameter, how did you set it at that time?

**Comment by iwangjian** [comment]
Hi, the `--gold_file <path_to_gold_data>` is the file path to the ground-truth dialogue utterances, e.g., `--gold_file data/DuRecDial2_en/sample_test_seen.jsonl`. Please refer to the updated README for more details.

**Comment by LLLLLearn** [comment]
Thank you very much for your reply, I read your updated readme file carefully
