### ISSUE TITLE
Hello author, I have encountered some problems in the process of replicating your paper experiment.I hope to get your reply

### ISSUE THREAD

**Issue by LLLLLearn** [iwangjian/TRIP#5]
Dear author, after receiving your reply yesterday, I carefully read your updated readme file, but I still have some questions and problems in the process of replicating the experiment, and it may take you a few minutes to answer them. Your response was critical for me to correctly reproduce this experiment, and my questions and problems are presented in the form of points below:
1. In your published dataset, the seen.jsonl and unseen.jsonl files correspond to the Text-IN and Text-OOD datasets in your paper, respectively? (Data set picture below) 
![数据集](https://github.com/user-attachments/assets/fbecf42f-ecba-404b-846c-cb016ad859b6)
2. In the planned path generation, if you want to generate the file best_model_test_unseen.jsonl, would you set the -test_data parameter to data/DuRecDial2_en/sample_text_unseen.jsonl? (Picture below)
 
![计划路径生成unseen](https://github.com/user-attachments/assets/72226713-c900-4faf-9cc8-1c38840cd890)

3. In dialog generation, to generate the file best_model_test_unseen.jsonl, To set these two parameters -- test_data to data/DuRecDial2_en/sample_text_unseen.jsonl and -- plan_data to outputs/DuRecDial2_en/plan/best_model_test_ unseen.jsonl? (Picture below)
 
![对话生成unseen](https://github.com/user-attachments/assets/d53f1296-a161-45bb-9c0a-e94eadca8b9f)

4. For the planned path generation evaluation function, if the -eval_file parameter is set to best_model_test_unseen.jsonl, should the corresponding -gold_file also be set to sample_test_unseen.jsonl? (Picture below)
 
![评估路径](https://github.com/user-attachments/assets/97120c95-682c-44b7-a635-2a5f420100ad)

5. In the DuRecDial2_en data set that you released, I cannot understand the dialogue_test_see.jsonl and sample_test_see.jsonl. Could you please explain the difference between the two files? For example, was the dialogue_test_see.jsonl used throughout the experiment? (Picture below)
 
![两个jsonl文件](https://github.com/user-attachments/assets/d3cf349a-ee28-48e5-847f-917548bdba73)

6. For the dialog generation evaluation function, I set the parameter --gold_file to sample_test_see.jsonl, but the result of the reproduction is very different from your paper (the training results are shown in the form of pictures below). I also tried to set the parameter --gold_file to dialogue_test_see.jsonl, but an error was reported (the error picture is shown below). Can the --gold_file parameter be set only to sample_text_see.jsonl and sample_text_unseen.jsonl for the dialog generation evaluation function?
 
![实验结果不一致](https://github.com/user-attachments/assets/6b32cd81-628b-468f-8b60-22ba030dabff)
![不一致论文参考](https://github.com/user-attachments/assets/66b53565-5648-41a0-969d-86e9eed2d5e5)
![不一致换参数](https://github.com/user-attachments/assets/6239339c-6e9a-4c56-8f93-f4bf1ee29b92)

 
 
7. In the dialog evaluation generation function, there is no result of PPL indicator (see the picture below), may I ask whether the author had PPL indicator when running the evaluation function?  
![没PPL](https://github.com/user-attachments/assets/bdec38de-8b64-4ec2-b38b-de383c30a4c8)

**Comment by iwangjian** [comment]
Hi, thanks for your interest.
1. Yes.
2. Yes.
3. Yes.
4. Yes.
5. The `dialogue_*.jsonl` covers raw dialogue data, where each line denotes a complete dialogue; the `sample_*.jsonl` is the preprocessed data where each multi-turn dialogue is split into multiple single-turn samples, making it easy to train and evaluate all different models.
6. This might be because the dialogue plan paths are not generated appropriately, which provide little guidance for dialogue generation. You may have a check for the evaluation of planning performance and then conduct dialogue generation. Note that `--gold_file` should be set to `sample_test_seen.jsonl` or `sample_test_unseen.jsonl`.
7. We are sorry the released code does not cover PPL. For this, you can implement the computation of PPL using the loss during testing.

**Comment by LLLLLearn** [comment]
Thank you for your meticulous response, author. I hope to successfully replicate the results in your paper. Wishing you a pleasant life and smooth research progress.
