### ISSUE TITLE
There are no PPL evaluation metrics in the eval_dialeg.py file in the published code

### ISSUE THREAD

**Issue by LLLLLearn** [iwangjian/TRIP#6]
Dear author, thank you very much for your reply last time. For your reply, I still have an unresolved question. I have tried many times to implement PPL in the eval_dialeg.py file without success. Could you please publish the code with PPL evaluation index?Thank you very much for your help.

**Comment by iwangjian** [comment]
Hi, you'd better add the evaluation of PPL during inference in the `main_dialog.py` because PPL is computed based on the inference-stage loss. We are sorry for not releasing this part, as this repo was completed and cleaned two years ago, and we cannot find the original version.

**Comment by LLLLLearn** [comment]
Thank you for your reply, I wish you smooth work and a happy life!
